// Optional end-to-end validation. Requires Playwright and Chromium.
// Run only against a NEW temporary data directory: creates fictional records.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');

(async()=>{
  const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:1050}});
  const page=await context.newPage(), errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
  const click=async action=>page.locator(`[data-action="${action}"]`).first().click();
  const fill=async (name,value)=>page.locator(`dialog[open] [name="${name}"]`).fill(value);
  const submit=async()=>{await page.locator('dialog[open] button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);};
  const nav=async id=>{if(await page.locator('.sidebar').evaluate(el=>el.inert))await click('mobile-menu');await page.locator(`.nav-button[data-id="${id}"]`).click();};
  try {
    await page.goto(process.env.AULA_TEST_URL||'http://127.0.0.1:8765');
    await page.waitForFunction(()=>{const img=document.querySelector('.brand img');return img?.complete&&img.naturalWidth>0;});
    assert.equal(await page.locator('.brand img').evaluate(img=>img.complete&&img.naturalWidth>0),true,'Logo on first opening');
    await page.getByLabel('Nombre del administrador').fill('María Administradora');
    await page.getByLabel('Usuario',{exact:true}).fill('admin');
    await page.getByLabel(/^Contraseña/).fill('Prueba-segura-2026');
    await page.getByRole('button',{name:'Crear mi cuenta'}).click();
    await page.locator('form[data-endpoint="confirm-rate"] [name="rate"]').fill('100');
    await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();
    await page.locator('.layout').waitFor();
    await page.reload();await page.locator('form[data-endpoint="confirm-rate"]').waitFor();assert.equal(await page.locator('.layout').count(),0);await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();await page.locator('.layout').waitFor();
    await nav('settings');
    assert.equal(await page.getByLabel('Razón social fiscal').inputValue(),'ALEJANDRO VON HUMBOLDT, C.A.');
    assert.equal(await page.getByLabel('RIF del colegio').inputValue(),'J-50835934-8');
    assert.match(await page.getByLabel('Domicilio fiscal',{exact:true}).inputValue(),/16-46/);
    await page.getByLabel('Nombre del colegio').fill('Colegio Los Cedros');
    await page.locator('form[data-endpoint="settings"] button[type="submit"]').click();
    await page.getByText('Registro guardado correctamente.').waitFor();
    const current=await page.evaluate(async()=>await(await fetch('/api/state')).json());
    const year=Number(current.settings.school_year), month=String(Number(current.settings.start_month)).padStart(2,'0');
    await nav('grades');await click('grade');await fill('name','Primaria · Sección A');await submit();
    await nav('guardians');await click('guardian');await fill('name','Ana Pérez');await fill('document','V-12345678');await fill('phone','04121234567');await submit();
    await nav('students');await click('student');await fill('name','Sofía Pérez');await fill('birth_date','2015-02-10');await fill('monthly_fee','50');await fill('discount','10');assert.match(await page.locator('#tuition-preview').innerText(),/45,00/);await fill('guardian_search','12345678');await page.locator('dialog[open] [name="guardian_id"]').selectOption({label:'V-12345678 · Ana Pérez'});await fill('enrollment_start',`${year}-${month}-01`);await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] .receipt-number').waitFor();assert.match(await page.locator('dialog[open] .receipt').innerText(),/AL-000001/);const enrollmentDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();const enrollmentPdf=await enrollmentDownload;await enrollmentPdf.saveAs('/tmp/aula-enrollment.pdf');await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('billing');
    const automatic=await page.evaluate(async()=>await(await fetch('/api/state')).json());
    const expectedMonths=(Number(current.today.slice(0,4))-year)*12+Number(current.today.slice(5,7))-Number(month)+1;
    assert.equal(automatic.charges.length,expectedMonths,'Enrollment must create elapsed monthly fees without clicking generate');
    assert.equal(automatic.students[0].balance,4500*expectedMonths);
    assert.equal(await page.getByRole('button',{name:'Preparar otro período',exact:true}).count(),1);
    await page.getByText('45,00',{exact:false}).first().waitFor();
    await click('rates');await fill('rate','100');await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] td').filter({hasText:'100'}).waitFor();
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('payments');await click('payment');await page.locator('dialog[open] [name="currency"]').selectOption('VES');await fill('amount','1000');await fill('reference','TR-001');
    await page.locator('dialog[open] button[type="submit"]').click();
    await page.locator('dialog[open] .receipt-number').waitFor();
    assert.match(await page.locator('dialog[open] .receipt').innerText(),/10,00/);
    assert.match(await page.locator('dialog[open] .receipt').innerText(),/100 por USD/);
    assert.match(await page.locator('dialog[open] .receipt-parties section').nth(1).innerText(),/Sofía Pérez.*Primaria · Sección A/);
    assert.match(await page.locator('dialog[open] .document-header').innerText(),/ALEJANDRO VON HUMBOLDT, C.A./);
    assert.match(await page.locator('dialog[open] .document-header').innerText(),/J-50835934-8/);
    assert.match(await page.locator('dialog[open] .document-header').innerText(),/local Nro. 16-46/);
    assert.equal(await page.locator('dialog[open] .school-emblem img').evaluate(img=>img.complete&&img.naturalWidth>0),true);
    assert.equal(await page.locator('#receipt-paper').inputValue(),'half-letter');
    assert.equal(await page.locator('#print-area .receipt-half-letter').count(),1);
    const halfDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await halfDownload).saveAs('/tmp/aula-half-letter.pdf');
    assert.ok(fs.readFileSync('/tmp/aula-half-letter.pdf').includes(Buffer.from('/MediaBox [0 0 612 396]')));

    await page.locator('#receipt-paper').selectOption('ticket-80');
    const ticketDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await ticketDownload).saveAs('/tmp/aula-ticket-80.pdf');
    assert.ok(fs.readFileSync('/tmp/aula-ticket-80.pdf').includes(Buffer.from('/MediaBox [0 0 226.772 ')));
    await page.locator('#receipt-paper').selectOption('ticket-58');
    const smallTicketDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await smallTicketDownload).saveAs('/tmp/aula-ticket-58.pdf');
    assert.ok(fs.readFileSync('/tmp/aula-ticket-58.pdf').includes(Buffer.from('/MediaBox [0 0 164.409 ')));
    await page.locator('#receipt-paper').selectOption('half-letter');
    await page.emulateMedia({media:'print'});
    await page.pdf({path:'/tmp/aula-print-half-letter.pdf',preferCSSPageSize:true,printBackground:true});
    await page.emulateMedia({media:'screen'});
    await page.locator('#receipt-paper').selectOption('a4');
    assert.equal(await page.locator('#print-area .receipt-half-letter').count(),0);
    assert.match(await page.getByRole('link',{name:'Descargar PDF'}).getAttribute('href'),/paper=a4/);
    await page.emulateMedia({media:'print'});
    await page.pdf({path:'/tmp/aula-print-receipt.pdf',format:'A4',printBackground:true});
    await page.emulateMedia({media:'screen'});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Receipt mobile overflow');
    assert.equal(await page.locator('dialog[open] .school-emblem img').isVisible(),true);
    await page.setViewportSize({width:1440,height:1050});
    const receiptDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await receiptDownload).saveAs('/tmp/aula-receipt.pdf');await page.screenshot({path:'/tmp/aula-receipt.png',fullPage:true});
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await click('payment');await fill('amount','5');
    await page.locator('dialog[open]').getByRole('button',{name:'Cancelar',exact:true}).click();
    assert.equal(await page.evaluate(async()=> (await(await fetch('/api/state')).json()).payments.length),1,'Cancel must not submit a payment');
    await nav('arrears');
    await page.locator('#page-content').getByText('Sofía Pérez',{exact:true}).waitFor();
    await click('collection');const balanceState=await page.evaluate(async()=>await(await fetch('/api/state')).json());assert.ok((await page.locator('#collection-text').inputValue()).includes(new Intl.NumberFormat('es-VE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(balanceState.students[0].overdue/100)));await page.locator('dialog[open] [data-action="close"]').first().click();
    await click('followup');await fill('note','Representante contactado; acordó abonar esta semana.');await submit();
    await nav('employees');await click('positions');await fill('name','Docente');await submit();await click('employee');await fill('name','José Docente');await fill('document','V-87654321');await page.locator('dialog[open] [name="position_id"]').selectOption({label:'Docente'});await fill('bank','Banco Prueba');await fill('bank_account','01020000000012345678');await fill('salary','100');await submit();
    await click('payroll-plan');assert.match(await page.locator('#payroll-total').innerText(),/10.000,00/);await page.locator('[data-payroll-employee]').fill('120');await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] .receipt-number').waitFor();assert.match(await page.locator('dialog[open] .receipt').innerText(),/12.000,00/);const payrollDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await payrollDownload).saveAs('/tmp/aula-payroll.pdf');await page.screenshot({path:'/tmp/aula-payroll.png',fullPage:true});await page.locator('dialog[open] [data-action="close"]').first().click();
    await click('payroll');assert.equal(await page.locator('dialog[open] [name="currency"]').inputValue(),'VES');await fill('amount','25');
    await fill('period_start',current.today.slice(0,7)+'-01');await fill('period_end',current.today);await fill('entry_time','07:00');await fill('exit_time','13:00');
    await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] .salary-document').waitFor();
    assert.match(await page.locator('dialog[open] .receipt').innerText(),/Recibí conforme/);assert.match(await page.locator('dialog[open] .receipt').innerText(),/07:00/);
    const salaryDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await salaryDownload).saveAs('/tmp/aula-salary-receipt.pdf');
    await page.screenshot({path:'/tmp/aula-salary-receipt.png',fullPage:true});await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('expenses');await click('salary-document');await page.locator('dialog[open] .salary-document').waitFor();await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('reports');await page.getByRole('heading',{name:'Reportes administrativos'}).waitFor();
    await page.evaluate(()=>window.print=()=>{});await click('print-report');
    assert.match(await page.locator('#print-area').textContent(),/J-50835934-8/);
    assert.equal(await page.locator('#print-area .school-emblem img').count(),1);

    await nav('guardians');await click('guardian-account');
    assert.match(await page.locator('dialog[open] .modal-body').innerText(),/Saldo familiar USD/);
    await click('issue-account');await page.locator('dialog[open] .receipt-number').waitFor();
    const familyDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await familyDownload).saveAs('/tmp/aula-family-account.pdf');
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('payments');await click('payment');await click('full-payment');
    await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] .receipt-number').waitFor();
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('guardians');await click('guardian-account');await click('issue-solvency');await page.locator('dialog[open] .receipt-number').waitFor();
    assert.match(await page.locator('dialog[open] .receipt').innerText(),/CONSTANCIA DE SOLVENCIA/);
    const solvencyDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await solvencyDownload).saveAs('/tmp/aula-solvency.pdf');
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('students');await click('import-roster');
    const header=await page.evaluate(async()=> (await fetch('/api/import-template')).text());
    const imported=['Beatriz Representante','V-999','04120009999','','','Mateo Importado','','2016-01-01','Primaria · Sección A',String(year),'50','10',`${year}-${month}-01`,`${year+1}-08-31`,'activo','Prueba de importación'];
    await page.locator('#roster-file').setInputFiles({name:'alumnos.csv',mimeType:'text/csv',buffer:Buffer.from(header+imported.join(';')+'\n')});
    await click('preview-import');await page.getByText('Sin errores de validación.',{exact:false}).waitFor();
    assert.equal(await page.evaluate(async()=> (await(await fetch('/api/state')).json()).students.length),1,'Preview must not save');
    await page.locator('#import-reviewed').check();await click('confirm-import');await page.locator('#page-content').getByText('Mateo Importado',{exact:true}).waitFor();
    assert.equal(await page.evaluate(async()=> (await(await fetch('/api/state')).json()).students.length),2);
    await nav('cash');await click('open-cash');await page.locator('form[data-endpoint="close-cash"]').waitFor();
    await fill('counted_USD','0');await fill('counted_VES','0');await page.locator('dialog[open] button[type="submit"]').click();
    await page.locator('dialog[open] .receipt-number').waitFor();
    assert.match(await page.locator('dialog[open] .receipt').innerText(),/Arqueo de efectivo/);
    const closeDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await closeDownload).saveAs('/tmp/aula-cash-close.pdf');
    await page.screenshot({path:'/tmp/aula-cash-close.png',fullPage:true});
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await click('reopen-cash');await fill('reason','Revisión de prueba');await submit();
    await nav('settings');assert.match(await page.locator('.data-path').innerText(),/colegio.sqlite3/);
    assert.match(await page.locator('.backup-status').innerText(),/Último respaldo/);

    // A past academic year provides a realistic promotion scenario without changing fixture dates.
    const apiPost=async(path,data)=>page.evaluate(async({path,data})=>{const session=await(await fetch('/api/session')).json();const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.user.csrf},body:JSON.stringify(data)});if(!r.ok)throw new Error(await r.text());return r.json();},{path,data});
    const latest=await page.evaluate(async()=>await(await fetch('/api/state')).json()),guardianId=latest.guardians.find(g=>g.name==='Ana Pérez').id,gradeId=latest.grades[0].id;
    const older=year-1,pastStudent={name:'Promoción Prueba',document:'A-PROMO',birth_date:'2015-01-01',guardian_id:guardianId,grade_id:gradeId,school_year:older,monthly_fee:'50',discount:'0',enrollment_start:`${older}-${month}-01`,enrollment_end:`${year}-08-31`,status:'active'};
    await apiPost('students',pastStudent);
    await nav('students');await page.reload();await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();await page.locator('.layout').waitFor();
    await nav('grades');await click('grade');await fill('name','Segundo · Sección A');await submit();
    await nav('students');await click('year-transition');await page.locator('#source-year').fill(String(older));await click('load-year');
    await page.locator('[data-map-grade]').selectOption({label:'Segundo · Sección A'});await click('preview-year');await page.locator('#year-reviewed').waitFor();
    assert.match(await page.locator('#year-preview').innerText(),/Promoción Prueba/);await page.screenshot({path:'/tmp/aula-year-preview.png',fullPage:true});
    await page.locator('#year-reviewed').check();await click('confirm-year');await page.locator('dialog[open] .receipt-number').waitFor();
    const promotionDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await promotionDownload).saveAs('/tmp/aula-year-transition.pdf');
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('arrears');const promoRow=page.locator('#page-content tr').filter({hasText:'Promoción Prueba'});await promoRow.locator('[data-action="payment-plan"]').click();
    await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] .receipt-number').waitFor();
    const planDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await planDownload).saveAs('/tmp/aula-payment-plan.pdf');
    assert.match(await page.locator('dialog[open] .modal-body').innerText(),/Cumplimiento actual/);
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('dashboard');
    fs.mkdirSync('/tmp/aula-artifacts',{recursive:true});
    await page.evaluate(()=>document.querySelector('#toast').className='');
    await page.screenshot({path:'/tmp/aula-artifacts/dashboard.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'/tmp/aula-artifacts/mobile.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile page overflow');
    await page.setViewportSize({width:1440,height:1050});
    await nav('settings');await click('user');await fill('name','Usuario Consulta');await fill('username','consulta');await fill('password','Consulta-segura');await page.locator('dialog[open] [name="role"]').selectOption('reader');await submit();
    await click('logout');await page.locator('.auth-form').getByLabel('Usuario',{exact:true}).fill('consulta');await page.locator('.auth-form').getByLabel(/^Contraseña/).fill('Consulta-segura');await page.getByRole('button',{name:'Iniciar sesión'}).click();await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();await page.locator('.layout').waitFor();
    assert.equal(await page.locator('.nav-button[data-id="settings"]').count(),0);
    assert.equal(await page.locator('[data-action="payment"]').count(),0);
    await click('logout');await page.locator('.auth-form').getByLabel('Usuario',{exact:true}).fill('admin');await page.locator('.auth-form').getByLabel(/^Contraseña/).fill('Prueba-segura-2026');
    await page.getByRole('button',{name:'Iniciar sesión'}).click();await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();await page.locator('.layout').waitFor();
    await nav('settings');await page.locator('.reset-settings summary').click();await click('reset-review');
    await page.locator('form[data-endpoint="reset-records"]').waitFor();await fill('password','Prueba-segura-2026');await fill('confirmation','VACIAR REGISTROS');
    await page.locator('dialog[open] input[type="checkbox"]').check();await page.locator('dialog[open] button[type="submit"]').click();
    await page.locator('.auth-form').waitFor();await page.locator('.auth-form').getByLabel('Usuario',{exact:true}).fill('admin');await page.locator('.auth-form').getByLabel(/^Contraseña/).fill('Prueba-segura-2026');
    await page.getByRole('button',{name:'Iniciar sesión'}).click();await page.getByLabel('Bolívares por 1 USD').fill('100');await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();await page.locator('.layout').waitFor();
    const cleaned=await page.evaluate(async()=>await(await fetch('/api/state')).json());assert.deepEqual(cleaned.students,[]);assert.deepEqual(cleaned.payments,[]);assert.deepEqual(cleaned.employees,[]);
    assert.equal(cleaned.users.length,2);assert.equal(cleaned.settings.rif,'J-50835934-8');
    assert.deepEqual(errors,[]);
    console.log('PASS: fiscal settings, PNG logo, fiscal letterheads and printing, daily rate checkpoint and reopening, guardian search, live discount, automatic student code, enrollment PDF, automatic arrears without manual monthly generation, BCV payment and receipt PDF, arrears, job catalogue, banks, consolidated payroll PDF and VES expense, reports, family account and solvency PDFs, CSV preview and import, cash close and reopening, backup status, thermal tickets, bulk promotion and archived PDF, payment plan, responsive layout, read-only role.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
