// Optional end-to-end validation. Requires Playwright and Chromium.
// Run only against a NEW temporary data directory: creates fictional records.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');

(async()=>{
  const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||(fs.existsSync('/usr/bin/chromium')?'/usr/bin/chromium':undefined),headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:1050}});
  const page=await context.newPage(), errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
  const click=async action=>page.locator(`[data-action="${action}"]`).first().click();
  const fill=async (name,value)=>page.locator(`dialog[open] [name="${name}"]`).fill(value);
  const submit=async()=>{await page.locator('dialog[open] button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('dialog').open);};
  const nav=async id=>{await page.locator(`.nav-button[data-id="${id}"]`).click();};
  try {
    await page.goto(process.env.AULA_TEST_URL||'http://127.0.0.1:8765');
    await page.waitForFunction(()=>{const img=document.querySelector('.brand img');return img?.complete&&img.naturalWidth>0;});
    assert.equal(await page.locator('.brand img').evaluate(img=>img.complete&&img.naturalWidth>0),true,'Logo on first opening');
    await page.getByLabel('Nombre del administrador').fill('María Administradora');
    await page.getByLabel('Usuario',{exact:true}).fill('admin');
    await page.getByLabel(/^Contraseña/).fill('Prueba-segura-2026');
    await page.getByRole('button',{name:'Crear mi cuenta'}).click();
    await page.locator('form[data-endpoint="confirm-rate"] [name="rate"]').fill('100');
    await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();
    await page.locator('.layout').waitFor();
    await page.reload();await page.locator('form[data-endpoint="confirm-rate"]').waitFor();assert.equal(await page.locator('.layout').count(),0);await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();await page.locator('.layout').waitFor();
    await nav('settings');
    assert.equal(await page.getByLabel('Razón social fiscal').inputValue(),'ALEJANDRO VON HUMBOLDT, C.A.');
    assert.equal(await page.getByLabel('RIF del colegio').inputValue(),'J-50835934-8');
    assert.match(await page.getByLabel('Domicilio fiscal',{exact:true}).inputValue(),/16-46/);
    await page.getByLabel('Nombre del colegio').fill('Colegio Los Cedros');
    await page.locator('form[data-endpoint="settings"] button[type="submit"]').click();
    await page.getByText('Registro guardado correctamente.').waitFor();
    const current=await page.evaluate(async()=>await(await fetch('/api/state')).json());
    const year=Number(current.settings.school_year), month=String(Number(current.settings.start_month)).padStart(2,'0');
    await nav('grades');await click('grade');await fill('name','Primaria · Sección A');await submit();
    await nav('guardians');await click('guardian');await fill('name','Ana Pérez');await fill('document','V-12345678');await fill('phone','04121234567');await submit();
    await nav('students');await click('student');await fill('name','Sofía Pérez');await fill('birth_date','2015-02-10');await fill('monthly_fee','50');await fill('discount','10');assert.match(await page.locator('#tuition-preview').innerText(),/45,00/);await fill('guardian_search','12345678');await page.locator('dialog[open] [name="guardian_id"]').selectOption({label:'V-12345678 · Ana Pérez'});await fill('enrollment_start',`${year}-${month}-01`);await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] .receipt-number').waitFor();assert.match(await page.locator('dialog[open] .receipt').innerText(),/AL-000001/);const enrollmentDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();const enrollmentPdf=await enrollmentDownload;await enrollmentPdf.saveAs('/tmp/aula-enrollment.pdf');await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('billing');
    const automatic=await page.evaluate(async()=>await(await fetch('/api/state')).json());
    const expectedMonths=(Number(current.today.slice(0,4))-year)*12+Number(current.today.slice(5,7))-Number(month)+1;
    assert.equal(automatic.charges.length,expectedMonths,'Enrollment must create elapsed monthly fees without clicking generate');
    assert.equal(automatic.students[0].balance,4500*expectedMonths);
    assert.equal(await page.getByRole('button',{name:'Preparar otro período',exact:true}).count(),1);
    await page.getByText('45,00',{exact:false}).first().waitFor();
    await click('rates');await fill('rate','100');await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] td').filter({hasText:'100'}).waitFor();
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await nav('payments');await click('payment');await page.locator('dialog[open] [name="currency"]').selectOption('VES');await fill('amount','1000');await fill('reference','TR-001');
    await page.locator('dialog[open] button[type="submit"]').click();
    await page.locator('dialog[open] .receipt-number').waitFor();
    assert.match(await page.locator('dialog[open] .receipt').innerText(),/10,00/);
    assert.match(await page.locator('dialog[open] .receipt').innerText(),/100 por USD/);
    assert.match(await page.locator('dialog[open] .document-header').innerText(),/ALEJANDRO VON HUMBOLDT, C.A./);
    assert.match(await page.locator('dialog[open] .document-header').innerText(),/J-50835934-8/);
    assert.match(await page.locator('dialog[open] .document-header').innerText(),/local Nro. 16-46/);
    assert.equal(await page.locator('dialog[open] .school-emblem img').evaluate(img=>img.complete&&img.naturalWidth>0),true);
    assert.equal(await page.locator('#receipt-paper').inputValue(),'half-letter');
    assert.equal(await page.locator('#print-area .receipt-half-letter').count(),1);
    const halfDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await halfDownload).saveAs('/tmp/aula-half-letter.pdf');
    assert.ok(fs.readFileSync('/tmp/aula-half-letter.pdf').includes(Buffer.from('/MediaBox [0 0 612 396]')));
    await page.emulateMedia({media:'print'});
    await page.pdf({path:'/tmp/aula-print-half-letter.pdf',preferCSSPageSize:true,printBackground:true});
    await page.emulateMedia({media:'screen'});
    await page.locator('#receipt-paper').selectOption('a4');
    assert.equal(await page.locator('#print-area .receipt-half-letter').count(),0);
    assert.match(await page.getByRole('link',{name:'Descargar PDF'}).getAttribute('href'),/paper=a4/);
    await page.emulateMedia({media:'print'});
    await page.pdf({path:'/tmp/aula-print-receipt.pdf',format:'A4',printBackground:true});
    await page.emulateMedia({media:'screen'});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Receipt mobile overflow');
    assert.equal(await page.locator('dialog[open] .school-emblem img').isVisible(),true);
    await page.setViewportSize({width:1440,height:1050});
    const receiptDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await receiptDownload).saveAs('/tmp/aula-receipt.pdf');await page.screenshot({path:'/tmp/aula-receipt.png',fullPage:true});
    await page.locator('dialog[open] [data-action="close"]').first().click();
    await click('payment');await fill('amount','5');
    await page.locator('dialog[open]').getByRole('button',{name:'Cancelar',exact:true}).click();
    assert.equal(await page.evaluate(async()=> (await(await fetch('/api/state')).json()).payments.length),1,'Cancel must not submit a payment');
    await nav('arrears');
    await page.locator('#page-content').getByText('Sofía Pérez',{exact:true}).waitFor();
    await click('collection');const balanceState=await page.evaluate(async()=>await(await fetch('/api/state')).json());assert.ok((await page.locator('#collection-text').inputValue()).includes(new Intl.NumberFormat('es-VE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(balanceState.students[0].overdue/100)));await page.locator('dialog[open] [data-action="close"]').first().click();
    await click('followup');await fill('note','Representante contactado; acordó abonar esta semana.');await submit();
    await nav('employees');await click('positions');await fill('name','Docente');await submit();await click('employee');await fill('name','José Docente');await fill('document','V-87654321');await page.locator('dialog[open] [name="position_id"]').selectOption({label:'Docente'});await fill('bank','Banco Prueba');await fill('bank_account','01020000000012345678');await fill('salary','100');await submit();
    await click('payroll-plan');assert.match(await page.locator('#payroll-total').innerText(),/10.000,00/);await page.locator('[data-payroll-employee]').fill('120');await page.locator('dialog[open] button[type="submit"]').click();await page.locator('dialog[open] .receipt-number').waitFor();assert.match(await page.locator('dialog[open] .receipt').innerText(),/12.000,00/);const payrollDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Descargar PDF'}).click();await(await payrollDownload).saveAs('/tmp/aula-payroll.pdf');await page.screenshot({path:'/tmp/aula-payroll.png',fullPage:true});await page.locator('dialog[open] [data-action="close"]').first().click();
    await click('payroll');assert.equal(await page.locator('dialog[open] [name="currency"]').inputValue(),'VES');await fill('amount','25');await submit();
    await nav('reports');await page.getByRole('heading',{name:'Reportes administrativos'}).waitFor();
    await page.evaluate(()=>window.print=()=>{});await click('print-report');
    assert.match(await page.locator('#print-area').textContent(),/J-50835934-8/);
    assert.equal(await page.locator('#print-area .school-emblem img').count(),1);
    await nav('dashboard');
    fs.mkdirSync('/tmp/aula-artifacts',{recursive:true});
    await page.evaluate(()=>document.querySelector('#toast').className='');
    await page.screenshot({path:'/tmp/aula-artifacts/dashboard.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'/tmp/aula-artifacts/mobile.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile page overflow');
    await page.setViewportSize({width:1440,height:1050});
    await nav('settings');await click('user');await fill('name','Usuario Consulta');await fill('username','consulta');await fill('password','Consulta-segura');await page.locator('dialog[open] [name="role"]').selectOption('reader');await submit();
    await click('logout');await page.locator('.auth-form').getByLabel('Usuario',{exact:true}).fill('consulta');await page.locator('.auth-form').getByLabel(/^Contraseña/).fill('Consulta-segura');await page.getByRole('button',{name:'Iniciar sesión'}).click();await page.getByRole('button',{name:'Confirmar tasa y entrar'}).click();await page.locator('.layout').waitFor();
    assert.equal(await page.locator('.nav-button[data-id="settings"]').count(),0);
    assert.equal(await page.locator('[data-action="payment"]').count(),0);
    assert.deepEqual(errors,[]);
    console.log('PASS: fiscal settings, PNG logo, fiscal letterheads and printing, daily rate checkpoint and reopening, guardian search, live discount, automatic student code, enrollment PDF, automatic arrears without manual monthly generation, BCV payment and receipt PDF, arrears, job catalogue, banks, consolidated payroll PDF and VES expense, reports, responsive layout, read-only role.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
