"""One source for the Excel instructions and in-app field guide."""
FIELDS = [
 ('representante_nombre','Sí','Nombre completo del representante legal.','Ana María Pérez'),
 ('representante_cedula','Sí','Cédula propia del representante; los hermanos repiten esta misma cédula y datos. Celda como Texto.','V-12345678'),
 ('representante_telefono','No','Teléfono como Texto para conservar el cero inicial.','04121234567'),
 ('representante_email','No','Correo del representante; puede quedar vacío.','ana@example.com'),
 ('representante_direccion','No','Dirección del representante; puede quedar vacía.','Sector Centro, Calle 10'),
 ('alumno_nombre','Sí','Nombre completo del alumno; una fila por alumno.','Sofía Pérez'),
 ('alumno_cedula','No','Cédula propia del alumno si la tiene. Nunca la del representante. Vacía: código AL automático. Celda como Texto.',''),
 ('nacimiento','No','Fecha real de nacimiento. AAAA-MM-DD como Texto o fecha de Excel; sin fórmulas. Si no la tienes, deja vacío: se mostrará Pendiente.','2016-04-23'),
 ('grado','Sí','Nombre completo EXACTO de un grado/sección ya creado en Aula.','1° PRIMARIA / A'),
 ('ano_escolar','Sí','Año en que comienza el ciclo: 2026 significa 2026–2027. Entero, sin guion.','2026'),
 ('mensualidad_usd','Sí','Mensualidad base en dólares, antes del descuento. Hasta dos decimales. Sin $ ni separadores de miles.','100.00'),
 ('descuento_pct','No','Porcentaje entero entre 0 y 100, sin %. Vacío = 0. No es el precio final.','10'),
 ('inicio_matricula','No','Inicio del período académico de referencia, no la fecha exacta de inscripción. Vacío = inicio del ciclo configurado. No determina el primer mes a cobrar.','2026-09-01'),
 ('fin_matricula','No','Fin del período, dentro del mismo ciclo. Vacío = fin del ciclo configurado.','2027-08-31'),
 ('estado','No','activo o inactivo. Vacío = activo. Los inactivos no generan mensualidades automáticas.','activo'),
 ('observaciones','No','Notas administrativas, sin fórmulas.','Beca aprobada del 10 %'),
 ('primer_mes_cobro','No','Primer mes que Aula generará, en AAAA-MM. Vacío = mes de carga (o inicio del período si es futuro). Los meses anteriores no se cobran automáticamente. Para años ya terminados debes elegir un mes del período.','2026-11'),
]

STEPS = [
 'Configura el año escolar, el mes de inicio y el vencimiento en Configuración antes de matricular.',
 'Crea los grados/secciones y su capacidad. Copia sus nombres exactos a la columna grado.',
 'Descarga la plantilla. Rellena únicamente la hoja Alumnos desde la fila 2; conserva sus 17 encabezados y su orden. La columna nueva es primer_mes_cobro; también se admite la plantilla anterior de 16 columnas.',
 'Las hojas Instrucciones, Ejemplos y Grados son de consulta y nunca se importan. Los ejemplos son ficticios.',
 'Usa una fila por alumno. Para hermanos, repite exactamente los datos del representante. Si ya existe, los datos deben coincidir con su ficha.',
 'No se importan pagos anteriores ni saldos históricos. Las mensualidades comienzan en primer_mes_cobro, independientemente del inicio del período académico. No hay prorrateo por días.',
 'Ejemplo: base 100 USD y descuento 10 generan 90 USD al mes. Período académico desde septiembre y primer_mes_cobro 2026-11: no se generan septiembre ni octubre. Vacío al cargar en noviembre también comienza en noviembre.',
 'Revisa el primer mes a cobrar y los cargos de la vista previa. Una deuda anterior se registra expresamente como cargo, o elige un mes anterior solo si esos meses realmente deben cobrarse. No inventes pagos para eliminar saldos.',
 'Guarda como .xlsx (recomendado) o CSV UTF-8. No .xls, macros, fórmulas, hojas protegidas ni columnas adicionales. Máximo 2 MB y 1000 alumnos por archivo.',
 'Pulsa Revisar archivo: no guarda datos. Corrige todas las filas señaladas, vuelve a seleccionar el archivo corregido y repite la revisión.',
 'Solo confirma cuando no haya errores y hayas comprobado nombres, fechas, tarifas y cargos. La confirmación guarda el lote completo; si falla una fila no se guarda ninguna.',
 'La importación crea alumnos nuevos; no actualiza fichas existentes. No importes el mismo archivo dos veces.',
]
